CREATE TABLE sysadm.udr_lta
(
   alt_rated_amount                 FLOAT (126),
   alt_rated_currency               INTEGER,
   alt_tariff_clicks_volume         FLOAT (126),
   alt_tmcode                       INTEGER,
   an_pack_an_package_id_list       VARCHAR2 (64 BYTE),
   an_pack_orig_an_pack_id_list     VARCHAR2 (64 BYTE),
   bal_audit_dat_balance_accum      FLOAT (126),
   bal_audit_dat_balance_prod_id    INTEGER,
   bal_audit_dat_bal_after_chg      FLOAT (126),
   bal_audit_dat_bal_before_chg     FLOAT (126),
   bal_audit_dat_bundl_prod_id      INTEGER,
   bal_audit_dat_contract_id        INTEGER,
   bal_audit_dat_purchase_seq_no    INTEGER,
   bal_audit_dat_user_profile_id    INTEGER,
   bop_info_bop_package_id          INTEGER,
   bop_info_bop_package_pkey        VARCHAR2 (10 BYTE),
   bop_info_bop_package_version     INTEGER,
   bop_info_detail_billed_ind       INTEGER,
   bop_info_detail_bop_altern_ind   INTEGER,
   bop_info_detail_contracted_ind   INTEGER,
   bop_info_detail_sequence_rp      INTEGER,
   bop_info_detail_sequence_sp      INTEGER,
   bop_tariff_info_day_catcode      VARCHAR2 (2 BYTE),
   bop_tariff_info_egcode           INTEGER,
   bop_tariff_info_egversion        INTEGER,
   bop_tariff_info_gvcode           INTEGER,
   bop_tariff_info_rpcode           INTEGER,
   bop_tariff_info_rpversion        INTEGER,
   bop_tariff_info_sncode           INTEGER,
   bop_tariff_info_spcode           INTEGER,
   bop_tariff_info_time_band_code   VARCHAR2 (2 BYTE),
   bop_tariff_info_tmcode           INTEGER,
   bop_tariff_info_tmversion        INTEGER,
   bop_tariff_info_tm_used_type     INTEGER,
   bop_tariff_info_twcode           INTEGER,
   bop_tariff_info_usage_ind        INTEGER,
   bop_tariff_info_zncode           INTEGER,
   bop_tariff_info_zpcode           INTEGER,
   bpartn_sum_info_time_slice_lb    INTEGER,
   bpartn_sum_info_time_slice_rb    INTEGER,
   bundle_info_bundle_purchase_id   VARCHAR2 (15 BYTE),
   bundle_info_bundle_purch_ind     INTEGER,
   bundle_info_contract_id          INTEGER,
   bundle_info_purchase_seq_no      INTEGER,
   bundle_info_sequence_number      INTEGER,
   bundle_info_sncode               INTEGER,
   bundle_info_state                VARCHAR2 (1 BYTE),
   bundle_info_termination          DATE,
   bundle_info_user_profile_id      INTEGER,
   bundle_info_valid_from           DATE,
   bundle_info_valid_to             DATE,
   bundle_info_version              INTEGER,
   bundle_usg_bundle_covered_usg    VARCHAR2 (1 BYTE),
   business_info_bs_id              INTEGER,
   business_info_c_p_field_ref      INTEGER,
   business_info_o_p_field_ref      INTEGER,
   bus_partner_info_tax_mode        INTEGER,
   call_dest                        VARCHAR2 (2 BYTE),
   call_type                        INTEGER,
   camel_dest_addr_user_prof_id     INTEGER,
   camel_msc_address                VARCHAR2 (100 BYTE),
   camel_msc_addr_user_prof_id      INTEGER,
   camel_reference_number           VARCHAR2 (16 BYTE),
   camel_srv_addr_user_prof_id      INTEGER,
   charge_info_cash_flow_direct     INTEGER,
   charge_info_disable_tax          INTEGER,
   charging_characteristics         VARCHAR2 (1 BYTE),
   content_advised_charge_ind       INTEGER,
   content_authorisation_code       VARCHAR2 (20 BYTE),
   content_content_charging_point   VARCHAR2 (1 BYTE),
   content_contract_pkey            VARCHAR2 (30 BYTE),
   content_desc_suppress            INTEGER,
   content_paid_ind                 INTEGER,
   content_payment_method           INTEGER,
   content_provider_address         VARCHAR2 (100 BYTE),
   content_provider_carrier_code    INTEGER,
   content_provider_clir            INTEGER,
   content_provider_iac             VARCHAR2 (10 BYTE),
   content_provider_modif_ind       INTEGER,
   content_provider_network_code    INTEGER,
   content_provid_dynamic_address   INTEGER,
   content_provid_local_pref_len    INTEGER,
   content_provid_numbering_plan    INTEGER,
   content_provid_other_location    VARCHAR2 (50 BYTE),
   content_provid_type_of_number    INTEGER,
   content_provid_user_profile_id   INTEGER,
   content_refund_ind               INTEGER,
   content_short_desc               VARCHAR2 (24 BYTE),
   content_transaction_id           VARCHAR2 (20 BYTE),
   cug_info_cug_id                  INTEGER,
   cug_info_cug_index               INTEGER,
   cust_info_address                VARCHAR2 (100 BYTE),
   cust_info_alternate_tmcode       INTEGER,
   cust_info_an_package_id_list     VARCHAR2 (64 BYTE),
   cust_info_bill_cycle             VARCHAR2 (2 BYTE) NOT NULL,
   cust_info_contract_id            INTEGER,
   cust_info_customer_id            INTEGER,
   cust_info_dn_id                  INTEGER,
   cust_info_main_msisdn            VARCHAR2 (65 BYTE),
   cust_info_numbering_plan         INTEGER,
   cust_info_port_id                INTEGER,
   cust_info_serv_bid_id            INTEGER,
   cust_info_subs_code              INTEGER,
   cust_info_subs_tag               INTEGER,
   cust_info_user_profile_id        INTEGER,
   data_volume                      FLOAT (126),
   data_volume_umcode               INTEGER,
   desc_prod_usage_long_desc        VARCHAR2 (500 BYTE),
   destination_field_id             INTEGER,
   downlink_volume_umcode           INTEGER,
   downlink_volume_volume           FLOAT (126),
   duration_umcode                  INTEGER,
   duration_volume                  FLOAT (126),
   entry_date_offset                INTEGER,
   entry_date_timestamp             DATE,
   event_info_event_type            INTEGER,
   event_status_info_message_id     INTEGER,
   event_umcode                     INTEGER,
   event_volume                     FLOAT (126),
   export_file                      VARCHAR2 (17 BYTE),
   follow_up_call_type              INTEGER,
   for_amount_amount                FLOAT (126),
   for_amount_currency              INTEGER,
   for_amount_gross_ind             INTEGER,
   for_amount_tax                   FLOAT (126),
   for_freechrg_amount              FLOAT (126),
   for_freechrg_currency            INTEGER,
   for_freechrg_gross_ind           INTEGER,
   for_freechrg_tax                 FLOAT (126),
   free_charge_amount               FLOAT (126),
   free_charge_currency             INTEGER,
   free_charge_gross_ind            INTEGER,
   free_charge_tax                  FLOAT (126),
   free_clicks_umcode               INTEGER,
   free_clicks_volume               FLOAT (126),
   free_rated_volume_umcode         INTEGER,
   free_rated_volume_volume         FLOAT (126),
   free_rounded_volume_umcode       INTEGER,
   free_rounded_volume_volume       FLOAT (126),
   free_units_info_account_key      INTEGER,
   free_units_info_account_origin   VARCHAR2 (1 BYTE),
   free_units_info_acc_hist_id      INTEGER,
   free_units_info_chg_red_quota    VARCHAR2 (1 BYTE),
   free_units_info_discount_rate    FLOAT (126),
   free_units_info_fup_seq          INTEGER,
   free_units_info_fu_pack_id       INTEGER,
   free_units_info_part_creator     VARCHAR2 (1 BYTE),
   free_units_info_previous_seqno   INTEGER,
   free_units_info_seqno            INTEGER,
   free_units_info_version          INTEGER,
   home_network_code                INTEGER,
   hscsd_info_aiur                  INTEGER,
   hscsd_info_channels_max          INTEGER,
   hscsd_info_channels_used         INTEGER,
   hscsd_info_coding_acc            INTEGER,
   hscsd_info_coding_used           INTEGER,
   hscsd_info_fnur                  INTEGER,
   hscsd_info_init_party            INTEGER,
   imp_party1_address               VARCHAR2 (100 BYTE),
   imp_party1_alternate_tmcode      INTEGER,
   imp_party1_an_package_id_list    VARCHAR2 (64 BYTE),
   imp_party1_bill_cycle            VARCHAR2 (2 BYTE),
   imp_party1_numbering_plan        INTEGER,
   imp_party1_user_profile_id       INTEGER,
   imp_party2_address               VARCHAR2 (100 BYTE),
   imp_party2_alternate_tmcode      INTEGER,
   imp_party2_an_package_id_list    VARCHAR2 (64 BYTE),
   imp_party2_bill_cycle            VARCHAR2 (2 BYTE),
   imp_party2_numbering_plan        INTEGER,
   imp_party2_user_profile_id       INTEGER,
   imp_party3_address               VARCHAR2 (100 BYTE),
   imp_party3_alternate_tmcode      INTEGER,
   imp_party3_an_package_id_list    VARCHAR2 (64 BYTE),
   imp_party3_bill_cycle            VARCHAR2 (2 BYTE),
   imp_party3_numbering_plan        INTEGER,
   imp_party3_user_profile_id       INTEGER,
   initial_start_time_timestamp     DATE,
   initial_start_time_time_offset   INTEGER,
   lcs_qos_deliv_horizontal_accur   INTEGER,
   lcs_qos_deliv_tracking_frequen   INTEGER,
   lcs_qos_deliv_tracking_period    INTEGER,
   lcs_qos_deliv_vertical_accur     INTEGER,
   lcs_qos_info_age_of_location     INTEGER,
   lcs_qos_info_position_method     INTEGER,
   lcs_qos_info_response_time       INTEGER,
   lcs_qos_info_response_time_cat   INTEGER,
   lcs_qos_req_horizontal_accur     INTEGER,
   lcs_qos_req_tracking_frequency   INTEGER,
   lcs_qos_req_tracking_period      INTEGER,
   lcs_qos_req_vertical_accur       INTEGER,
   ldc_info_carrier_code            INTEGER,
   lzlist                           VARCHAR2 (40 BYTE),
   mc_info_code                     INTEGER,
   mc_info_ind                      INTEGER,
   mc_scalefactor                   FLOAT (126),
   messages_umcode                  INTEGER,
   messages_volume                  FLOAT (126),
   network_init_context_ind         INTEGER,
   net_element_home_bid_id          INTEGER,
   net_element_network_code         INTEGER,
   net_element_netw_element_id      INTEGER,
   net_element_user_profile_id      INTEGER,
   normed_net_elem_address          VARCHAR2 (100 BYTE),
   normed_net_elem_int_acc_code     VARCHAR2 (10 BYTE),
   normed_net_elem_number_plan      INTEGER,
   normed_rtd_num_address           VARCHAR2 (100 BYTE),
   normed_rtd_num_int_acc_code      VARCHAR2 (10 BYTE),
   normed_rtd_num_number_plan       INTEGER,
   origin_field_id                  INTEGER,
   or_flag                          INTEGER,
   o_p_normed_num_address           VARCHAR2 (100 BYTE),
   o_p_normed_num_int_acc_code      VARCHAR2 (10 BYTE),
   o_p_normed_num_number_plan       INTEGER,
   o_p_number_address               VARCHAR2 (100 BYTE),
   o_p_number_backup_address        VARCHAR2 (100 BYTE),
   o_p_number_carrier_code          INTEGER,
   o_p_number_clir                  INTEGER,
   o_p_number_numbering_plan        INTEGER,
   o_p_number_other_location        VARCHAR2 (50 BYTE),
   o_p_number_type_of_number        INTEGER,
   o_p_number_user_profile_id       INTEGER,
   promo_info_b_number_cat          INTEGER,
   qos_negot_delay                  INTEGER,
   qos_negot_mean_throughput        INTEGER,
   qos_negot_peak_throughput        INTEGER,
   qos_negot_precedence             INTEGER,
   qos_negot_reliability            INTEGER,
   qos_profile                      INTEGER,
   qos_req_delay                    INTEGER,
   qos_req_mean_throughput          INTEGER,
   qos_req_peak_throughput          INTEGER,
   qos_req_precedence               INTEGER,
   qos_req_reliability              INTEGER,
   rated_clicks_umcode              INTEGER,
   rated_clicks_volume              FLOAT (126),
   rated_flat_amnt_orig_currency    INTEGER,
   rated_flat_amnt_orig_gross_ind   INTEGER,
   rated_flat_amount                FLOAT (126),
   rated_flat_amount_currency       INTEGER,
   rated_flat_amount_gross_ind      INTEGER,
   rated_flat_amount_orig_amount    FLOAT (126),
   rated_flat_amount_orig_tax       FLOAT (126),
   rated_flat_amount_tax            FLOAT (126),
   rated_volume                     FLOAT (126),
   rated_volume_umcode              INTEGER,
   recipient_net_address            VARCHAR2 (100 BYTE),
   recipient_net_numbering_plan     INTEGER,
   record_id_call_id                INTEGER,
   record_id_cdr_id                 INTEGER,
   record_id_cdr_sub_id             INTEGER,
   record_id_orig_cdr_id            INTEGER,
   record_id_rap_sequence_num       INTEGER,
   record_id_tap_sequence_num       INTEGER,
   record_id_udr_file_id            INTEGER,
   refer_contr_contract_id          INTEGER,
   refer_contr_reference_type       INTEGER,
   rejected_base_part               INTEGER,
   reject_reason_code               VARCHAR2 (5 BYTE),
   remark                           VARCHAR2 (80 BYTE),
   rounded_volume                   FLOAT (126),
   rounded_volume_umcode            INTEGER,
   routing_network_code             INTEGER,
   routing_number_backup_address    VARCHAR2 (100 BYTE),
   routing_user_profile_id          INTEGER,
   scu_id_address                   VARCHAR2 (100 BYTE),
   scu_id_user_profile_id           INTEGER,
   scu_info_priority_code           INTEGER,
   service_action_code              VARCHAR2 (1 BYTE),
   service_guaranteed_bit_rate      INTEGER,
   service_hscsd_ind                INTEGER,
   service_ims_signalling_context   INTEGER,
   service_logic_code               VARCHAR2 (50 BYTE),
   service_max_bit_rate             INTEGER,
   service_service_type             VARCHAR2 (1 BYTE),
   service_used_service             INTEGER,
   service_user_protocol_ind        INTEGER,
   service_vas_code                 VARCHAR2 (10 BYTE),
   serv_pdp_addr_apn_split_ind      INTEGER,
   sgsn_addresses                   VARCHAR2 (64 BYTE),
   spec_num_info_apply_free_units   INTEGER,
   start_time_charge_offset         INTEGER,
   start_time_charge_timestamp      DATE,
   start_time_offset                INTEGER,
   start_time_timestamp             DATE,
   s_pdp_address                    VARCHAR2 (100 BYTE),
   s_pdp_carrier_code               INTEGER,
   s_pdp_clir                       INTEGER,
   s_pdp_intern_access_code         VARCHAR2 (10 BYTE),
   s_pdp_modification_ind           INTEGER,
   s_pdp_network_code               INTEGER,
   s_pdp_numbering_plan             INTEGER,
   s_pdp_type_of_number             INTEGER,
   s_pdp_user_profile_id            INTEGER,
   s_p_equipment_class_mark         VARCHAR2 (1 BYTE),
   s_p_equipment_number             VARCHAR2 (20 BYTE),
   s_p_home_id_description          VARCHAR2 (30 BYTE),
   s_p_home_id_home_bid_id          INTEGER,
   s_p_home_id_name                 VARCHAR2 (24 BYTE),
   s_p_home_id_network              VARCHAR2 (5 BYTE),
   s_p_home_loc_address             VARCHAR2 (100 BYTE),
   s_p_home_loc_numbering_plan      INTEGER,
   s_p_location_address             VARCHAR2 (100 BYTE),
   s_p_location_numbering_plan      INTEGER,
   s_p_loc_serving_bid_id           INTEGER,
   s_p_loc_serving_location         VARCHAR2 (50 BYTE),
   s_p_number_address               VARCHAR2 (100 BYTE),
   s_p_number_home_bid_id           INTEGER,
   s_p_number_network_code          INTEGER,
   s_p_number_numbering_plan        INTEGER,
   s_p_number_user_profile_id       INTEGER,
   s_p_port_address                 VARCHAR2 (100 BYTE),
   s_p_port_user_profile_id         INTEGER,
   tariff_detail_chgbl_quantity     INTEGER,
   tariff_detail_ext_chrg_udmcode   INTEGER,
   tariff_detail_interconnect_ind   VARCHAR2 (1 BYTE),
   tariff_detail_rate_type_id       INTEGER,
   tariff_detail_rtx_charge_type    VARCHAR2 (1 BYTE),
   tariff_detail_ttcode             INTEGER,
   tariff_info_catalogue_id         INTEGER,
   tariff_info_catalogue_vers       INTEGER,
   tariff_info_ctlg_elm_id          INTEGER,
   tariff_info_egcode               INTEGER,
   tariff_info_egversion            INTEGER,
   tariff_info_gvcode               INTEGER,
   tariff_info_pricelist_id         INTEGER,
   tariff_info_pricelist_pkey       VARCHAR2 (16 BYTE),
   tariff_info_pricelist_vers       INTEGER,
   tariff_info_price_def_vers       INTEGER,
   tariff_info_rpcode               INTEGER,
   tariff_info_rpversion            INTEGER,
   tariff_info_sncode               INTEGER,
   tariff_info_spcode               INTEGER,
   tariff_info_time_band_code       VARCHAR2 (2 BYTE),
   tariff_info_tmcode               INTEGER,
   tariff_info_tmversion            INTEGER,
   tariff_info_tm_used_type         INTEGER,
   tariff_info_twcode               INTEGER,
   tariff_info_usage_ind            INTEGER,
   tariff_info_zncode               INTEGER,
   tariff_info_zpcode               INTEGER,
   tariff_info_zpcode_day_catcode   VARCHAR2 (2 BYTE),
   tax_info_serv_cat                VARCHAR2 (10 BYTE),
   tax_info_serv_code               VARCHAR2 (10 BYTE),
   tax_info_serv_type               VARCHAR2 (3 BYTE),
   techn_info_prepay_ind            VARCHAR2 (1 BYTE),
   techn_info_pre_rated_ind         INTEGER,
   techn_info_rev_charging_ind      INTEGER,
   techn_info_sccode                INTEGER,
   techn_info_termination_ind       INTEGER,
   t_p_number_user_profile_id       INTEGER,
   udr_basepart_id                  INTEGER,
   udr_chargepart_id                INTEGER,
   uds_base_part_id                 INTEGER,
   uds_charge_part_id               INTEGER,
   uds_free_unit_part_id            INTEGER,
   uds_record_id                    INTEGER,
   uds_stream_id                    INTEGER,
   umts_qos_negot_allc_retn_prior   INTEGER,
   umts_qos_negot_delay             INTEGER,
   umts_qos_negot_delivery_order    INTEGER,
   umts_qos_negot_erroneous_sdus    INTEGER,
   umts_qos_negot_handl_priority    INTEGER,
   umts_qos_negot_max_size_sdu      INTEGER,
   umts_qos_negot_rate_downlink     INTEGER,
   umts_qos_negot_rate_uplink       INTEGER,
   umts_qos_negot_residual_ber      INTEGER,
   umts_qos_negot_sdu_err_ratio     INTEGER,
   umts_qos_negot_traffic_class     INTEGER,
   umts_qos_req_allc_retn_prior     INTEGER,
   umts_qos_req_delay               INTEGER,
   umts_qos_req_delivery_order      INTEGER,
   umts_qos_req_erroneous_sdus      INTEGER,
   umts_qos_req_handl_priority      INTEGER,
   umts_qos_req_max_size_sdu        INTEGER,
   umts_qos_req_rate_downlink       INTEGER,
   umts_qos_req_rate_uplink         INTEGER,
   umts_qos_req_residual_ber        INTEGER,
   umts_qos_req_sdu_error_ratio     INTEGER,
   umts_qos_req_traffic_class       INTEGER,
   unbilled_amount_amount           FLOAT (126),
   unbilled_amount_currency         INTEGER,
   unbilled_amount_gross_ind        INTEGER,
   unbilled_amount_tax              FLOAT (126),
   uplink_volume_umcode             INTEGER,
   uplink_volume_volume             FLOAT (126),
   vpn_info_vpn_call_type           INTEGER,
   vpn_number_address               VARCHAR2 (100 BYTE),
   vpn_number_carrier_code          INTEGER,
   vpn_number_clir                  INTEGER,
   vpn_number_dynamic_address       INTEGER,
   vpn_number_int_access_code       VARCHAR2 (10 BYTE),
   vpn_number_local_prefix_len      INTEGER,
   vpn_number_modification_ind      INTEGER,
   vpn_number_network_code          INTEGER,
   vpn_number_numbering_plan        INTEGER,
   vpn_number_type_of_number        INTEGER,
   vpn_number_user_profile_id       INTEGER,
   xfile_base_charge_amount         FLOAT (126),
   xfile_base_charge_currency       INTEGER,
   xfile_base_charge_gross_ind      INTEGER,
   xfile_base_charge_tax            FLOAT (126),
   xfile_call_type                  VARCHAR2 (2 BYTE),
   xfile_charge_amount              FLOAT (126),
   xfile_charge_currency            INTEGER,
   xfile_charge_gross_ind           INTEGER,
   xfile_charge_tax                 FLOAT (126),
   xfile_day_category_code          VARCHAR2 (2 BYTE),
   xfile_discount_amount            FLOAT (126),
   xfile_discount_currency          INTEGER,
   xfile_ic_charge_amount           FLOAT (126),
   xfile_ic_charge_currency         INTEGER,
   xfile_ic_charge_gross_ind        INTEGER,
   xfile_ic_charge_tax              FLOAT (126),
   xfile_ind                        VARCHAR2 (1 BYTE),
   xfile_time_band_code             VARCHAR2 (2 BYTE),
   zero_rated_volume_umcode         INTEGER,
   zero_rated_volume_volume         FLOAT (126),
   zero_rounded_volume_umcode       INTEGER,
   zero_rounded_volume_volume       FLOAT (126),
   cust_info_parent_contract_id     INTEGER,
   imp_party1_parent_contract_id    INTEGER,
   imp_party2_parent_contract_id    INTEGER,
   imp_party3_parent_contract_id    INTEGER,
   number_of_rejections             INTEGER,
   tz_dn_int_acc_code               VARCHAR2 (10 BYTE),
   mnp_rn_carrier_code              INTEGER,
   mnp_rn_clir                      INTEGER,
   mnp_rn_type_of_number            INTEGER,
   mnp_rn_numbering_plan            INTEGER,
   mnp_rn_address                   VARCHAR2 (100 BYTE),
   tz_dn_address                    VARCHAR2 (100 BYTE),
   tz_dn_number_plan                NUMBER
)
TABLESPACE udr_lt_heap_ts_06
PCTUSED 0
PCTFREE 10
INITRANS 40
MAXTRANS 255
STORAGE (BUFFER_POOL DEFAULT)
PARTITION BY RANGE
   (entry_date_timestamp)
   (
      PARTITION udr_lta_w13
         VALUES LESS THAN
            (TO_DATE (' 2013-04-08 00:00:00', 'SYYYY-MM-DD HH24:MI:SS',
             'NLS_CALENDAR=GREGORIAN'))
         LOGGING
         NOCOMPRESS
         TABLESPACE udr_lt_heap_ts_01
         PCTFREE 0
         INITRANS 40
         MAXTRANS 255
         STORAGE (INITIAL 64 K MINEXTENTS 1 MAXEXTENTS UNLIMITED
         BUFFER_POOL DEFAULT))
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX sysadm.pk_udr_lta_part
   ON sysadm.udr_lta (cust_info_customer_id, cust_info_contract_id,
   uds_stream_id, uds_record_id, uds_base_part_id, uds_charge_part_id,
   uds_free_unit_part_id, entry_date_timestamp)
   PCTFREE 10
   INITRANS 40
   MAXTRANS 255
   STORAGE (BUFFER_POOL DEFAULT)
   LOGGING
   LOCAL (PARTITION udr_lta_w13
             LOGGING
             COMPRESS
             TABLESPACE udr_lt_heap_ts_01
             PCTFREE 10
             INITRANS 40
             MAXTRANS 255
             STORAGE (INITIAL 64 K MINEXTENTS 1 MAXEXTENTS UNLIMITED
             BUFFER_POOL DEFAULT))
   NOPARALLEL
   COMPRESS 2;

CREATE INDEX sysadm.udr_lta_heap_cust_contr_ts_idx
   ON sysadm.udr_lta (cust_info_customer_id, cust_info_contract_id,
   "ENTRY_DATE_TIMESTAMP" + "ENTRY_DATE_OFFSET" / 86400)
   PCTFREE 10
   INITRANS 40
   MAXTRANS 255
   STORAGE (BUFFER_POOL DEFAULT)
   LOGGING
   LOCAL (PARTITION udr_lt_w13
             LOGGING
             COMPRESS
             TABLESPACE udr_lt_heap_ts_01
             PCTFREE 10
             INITRANS 40
             MAXTRANS 255
             STORAGE (INITIAL 64 K MINEXTENTS 1 MAXEXTENTS UNLIMITED
             BUFFER_POOL DEFAULT))
   NOPARALLEL
   COMPRESS 2;

ALTER TABLE sysadm.udr_lta ADD (
  CONSTRAINT pk_udr_lta_part
  PRIMARY KEY
  (cust_info_customer_id, cust_info_contract_id, uds_stream_id, uds_record_id, uds_base_part_id, uds_charge_part_id, uds_free_unit_part_id, entry_date_timestamp)
  USING INDEX LOCAL
  ENABLE NOVALIDATE);

GRANT SELECT, UPDATE ON sysadm.udr_lta TO alcatel;

GRANT DELETE, INSERT, SELECT, UPDATE ON sysadm.udr_lta TO bscs_role;

GRANT DELETE, INSERT, SELECT, UPDATE ON sysadm.udr_lta TO rlh;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE,
   ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK,
   ON sysadm.udr_lta
   TO bscs6;

INSERT INTO udr_lta
   SELECT *
     FROM udr_lt PARTITION (udr_lt_w13)
    WHERE ROWNUM < 10000;

ALTER TABLE udr_lt RENAME TO udr_lto;

ALTER TABLE udr_lta RENAME TO udr_lt;